---
title: "in_class_exc8"
output: md_document
---
## Readin gin data file

```{r}


```
adsasd
```{r}
cocoli_dat <- read.table("~/Desktop/eeb-177/class-assignments/classwork-21-Feb/cocoli.txt", header = TRUE)
cocoli_dat
sizes_in_94 <- cocoli_dat$dbh1
names(sizes_in_94) <- cocoli_dat$tag
sizes_in_94["000009"]
sizes_in_94[c("000009", "000099")]

sizes_in_97 <-cocoli_dat$dbh2

rgr_1 <-((sizes_in_97-sizes_in_94)/sizes_in_94)/3
rgr_1
cocoli_dat$rgr_1 <- rgr_1
cocoli_dat
```


```{r}
# bar graph- make with barplot()
#box plot - make with boxplot()
#scatterplot- make with plot()
#histogram- mae with hist()

hist(sizes_in_94, xlab = "DBH (mm)", main = "Distribution of tree sizes in cocoli (1994)")

plot(x= sizes_in_94, y= sizes_in_97, main = "scatterplot of sizes", xlab = "sizes in 1994 (mm)", ylab = "Sizes in 1997", pch = 19, col = "blue", log ="xy")

```


```{r}
library(dplyr)
# %>% is identical to the | in terminal
cocoli_dat %>% filter(sizes_in_94 > 0) %>% arrange(-dbh1) %>% group_by(spcode)%>% summarize(mean_dbh_1994= mean(dbh1))


```

```{r}

cocoli_dat %>% filter(dbh1 > 0) %>% group_by(spcode)%>% summarize(mean_dbh_1994= mean(dbh1))



```

